/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stego;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Enigmatic Hunk
 */
public class intface extends javax.swing.JFrame {

    /**
     * Creates new form intface
     */
    public String hashmd,cipher;
    public intface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPanel1 = new javax.swing.JPanel();
        browsetextbutton = new javax.swing.JButton();
        browsetextfield = new javax.swing.JTextField();
        browseimagefield = new javax.swing.JTextField();
        browseimagebutton = new javax.swing.JButton();
        pubkeylab = new javax.swing.JLabel();
        publickeyfield = new javax.swing.JTextField();
        jFileChooser2 = new javax.swing.JFileChooser();
        jFileChooser3 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        embedbutton = new javax.swing.JButton();
        exitbutton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        sendmodfield = new javax.swing.JTextField();
        imglabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        authcodefield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        browsestegofield = new javax.swing.JTextField();
        browsestegobutton = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel4 = new javax.swing.JLabel();
        privatekeyfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        outputfield = new javax.swing.JTextField();
        outputbutton = new javax.swing.JButton();
        jFileChooser4 = new javax.swing.JFileChooser();
        extractbutton = new javax.swing.JButton();
        exitbutton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        mdfcodefield = new javax.swing.JTextField();
        recmodfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        keysizefield = new javax.swing.JTextField();
        pubgenfield = new javax.swing.JTextField();
        privgenfield = new javax.swing.JTextField();
        modgenfield = new javax.swing.JTextField();
        genkeybutton = new javax.swing.JButton();
        exitbutton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        browsetextbutton.setText("Browse.");
        browsetextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsetextbuttonActionPerformed(evt);
            }
        });

        browsetextfield.setText("Open your text file...");
        browsetextfield.setToolTipText("");
        browsetextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsetextfieldActionPerformed(evt);
            }
        });

        browseimagefield.setText("Open your Cover Image..");
        browseimagefield.setToolTipText("");

        browseimagebutton.setText("Browse..");
        browseimagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseimagebuttonActionPerformed(evt);
            }
        });

        pubkeylab.setText("Public Key:");

        publickeyfield.setText("Enter your key..");

        jLabel1.setText("Text File Location:");

        jLabel2.setText("Location for Image to be processed:");

        embedbutton.setText("Embed the text in image..");
        embedbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embedbuttonActionPerformed(evt);
            }
        });

        exitbutton1.setText("Exit");
        exitbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Modulus:");

        sendmodfield.setText("Enter the mod of primes..");

        jLabel13.setText("Authentication Code:");

        authcodefield.setText(" ");

        txtarea.setColumns(20);
        txtarea.setRows(5);
        txtarea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtarea);

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(authcodefield, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(JPanel1Layout.createSequentialGroup()
                                            .addComponent(embedbutton)
                                            .addGap(18, 18, 18)
                                            .addComponent(exitbutton1))
                                        .addGroup(JPanel1Layout.createSequentialGroup()
                                            .addComponent(pubkeylab)
                                            .addGap(242, 242, 242)))
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sendmodfield, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)))))
                        .addGap(19, 19, 19))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(browsetextfield)
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(browseimagefield))
                                .addGap(18, 18, 18)
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(browseimagebutton)
                                    .addComponent(browsetextbutton)))
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(publickeyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pubkeylab)
                                    .addComponent(publickeyfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49))
                            .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sendmodfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel1Layout.createSequentialGroup()
                                    .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(browsetextbutton)
                                        .addComponent(browsetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFileChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(JPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(browseimagefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(browseimagebutton))))
                                    .addGap(104, 104, 104))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(9, 9, 9)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(embedbutton)
                    .addComponent(exitbutton1)
                    .addComponent(authcodefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        imglabel.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Hiding the Text", JPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Stego Image Location:");

        browsestegofield.setText("Open your file to be extracted..");

        browsestegobutton.setText("Browse..");
        browsestegobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsestegobuttonActionPerformed(evt);
            }
        });

        jLabel4.setText("Private Key:");

        privatekeyfield.setText("Enter your key...");

        jLabel5.setText("Output Location:");

        outputfield.setText("Select the folder for output...");

        outputbutton.setText("Browse..");
        outputbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputbuttonActionPerformed(evt);
            }
        });

        extractbutton.setText("Extract the text..");
        extractbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractbuttonActionPerformed(evt);
            }
        });

        exitbutton2.setText("Exit");
        exitbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Hash Code:");

        mdfcodefield.setText("Enter the auth code...");

        recmodfield.setText("Enter the mod of primes..");

        jLabel12.setText("Modulus:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(browsestegofield)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(outputfield)
                                        .addGap(19, 19, 19)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(browsestegobutton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outputbutton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                                .addComponent(jFileChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(extractbutton)
                                .addGap(23, 23, 23)
                                .addComponent(exitbutton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recmodfield, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(privatekeyfield)
                                    .addComponent(mdfcodefield))))
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browsestegofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browsestegobutton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(privatekeyfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jFileChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(outputbutton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recmodfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mdfcodefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extractbutton)
                    .addComponent(exitbutton2))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Extracting the Text", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(""), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel6.setText("Public Key:");

        jLabel7.setText("Private Key:");

        jLabel8.setText("Modulus:");

        jLabel9.setText("Key Size:");

        keysizefield.setText("Enter your key size...");
        keysizefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keysizefieldActionPerformed(evt);
            }
        });

        pubgenfield.setText("The sender's key...");

        privgenfield.setText("The receiver's key..");

        modgenfield.setText("Modulus value of primes..");

        genkeybutton.setText("Generate Key");
        genkeybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genkeybuttonActionPerformed(evt);
            }
        });

        exitbutton3.setText("Exit");
        exitbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(genkeybutton)
                .addGap(258, 258, 258))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitbutton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(privgenfield)
                                    .addComponent(modgenfield, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pubgenfield)
                                    .addComponent(keysizefield))))))
                .addGap(73, 73, 73))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(keysizefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(genkeybutton)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pubgenfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(privgenfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(modgenfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(exitbutton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("RSA Key Generation", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browsetextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsetextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_browsetextfieldActionPerformed

    private void browsetextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsetextbuttonActionPerformed
        // TODO add your handling code here:
        int answer = jFileChooser2.showOpenDialog(this);
              if (answer == JFileChooser.APPROVE_OPTION)
                   {
                        File file = jFileChooser2.getSelectedFile();
                        browsetextfield.setText(file.getAbsolutePath());
                   }
              String text;
         
        try(BufferedReader br = new BufferedReader(new FileReader(browsetextfield.getText()))) 
      	{
        StringBuilder sb = new StringBuilder();
        String line = br.readLine();

        while (line != null) {
        	
            sb.append(line);
            sb.append(System.lineSeparator());
            line = br.readLine();
        }
        text = sb.toString();
        txtarea.setText(text);
        }
        
        catch(Exception e)
        {}
        
    }//GEN-LAST:event_browsetextbuttonActionPerformed

    private void browseimagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseimagebuttonActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG Images (*.jpg)", "jpg");
                       jFileChooser3.setFileFilter(filter);
        int answer = jFileChooser3.showOpenDialog(this);
              if (answer == JFileChooser.APPROVE_OPTION)
                   {
                       
                        File file = jFileChooser3.getSelectedFile();
                        
                        browseimagefield.setText(file.getAbsolutePath());
                        ImageIcon image = new ImageIcon(file.getAbsolutePath());
                        Image img=image.getImage();
                        Image scaimg=img.getScaledInstance(350, 250,  java.awt.Image.SCALE_SMOOTH);
                        image=new ImageIcon(scaimg);
                        imglabel=new JLabel();
                        imglabel.setIcon(image);
                        //imglabel.setSize(250, 250);
                        imglabel.setBounds(20,200,350,250);
                        imglabel.setVisible(true);
                        JPanel1.add(imglabel);
                        repaint();
                        
                        
                   }
    }//GEN-LAST:event_browseimagebuttonActionPerformed

    private void embedbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embedbuttonActionPerformed
        try {
            // TODO add your handling code here:
            cipher=rsa.RSAencrypt(publickeyfield.getText(), sendmodfield.getText(), new FileReader(browsetextfield.getText()));
            //System.out.println("ciph"+cipher);
            //cipher="abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz";
            hashmd=mdfive.calculateauth(new FileReader(browseimagefield.getText()));
            Embedding.embed(new File(browseimagefield.getText()), cipher, hashmd);
        } catch (Exception ex) {
            Logger.getLogger(intface.class.getName()).log(Level.SEVERE, null, ex);
        }
          authcodefield.setText(hashmd);
        
    }//GEN-LAST:event_embedbuttonActionPerformed

    private void exitbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbutton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbutton1ActionPerformed

    private void browsestegobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsestegobuttonActionPerformed
        // TODO add your handling code here:
        int answer = jFileChooser1.showOpenDialog(this);
              if (answer == JFileChooser.APPROVE_OPTION)
                   {
                        File file = jFileChooser1.getSelectedFile();
                        browsestegofield.setText(file.getAbsolutePath());
                   }
    }//GEN-LAST:event_browsestegobuttonActionPerformed

    private void outputbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputbuttonActionPerformed
        // TODO add your handling code here:
        jFileChooser4.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int answer = jFileChooser4.showOpenDialog(this);
              if (answer == JFileChooser.APPROVE_OPTION)
                   {
                        File file = jFileChooser4.getSelectedFile();
                        outputfield.setText(file.getPath());
                   }
       
    }//GEN-LAST:event_outputbuttonActionPerformed

    private void keysizefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keysizefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keysizefieldActionPerformed

    private void genkeybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genkeybuttonActionPerformed
        // TODO add your handling code here:
        
        rsakeygen rsak;
        rsak = new rsakeygen();
        rsak.gen(Integer.parseInt(keysizefield.getText()));
        /*byte[] eb=rsak.e.toByteArray();
        System.out.println(rsak.e.toString(2));
        String one=new String(rsak.e.toString());
               //byte[] db=rsak.d.toByteArray();
              //byte[] nb=rsak.n.toByteArray();
              //StringBuilder sb=new StringBuilder();
          //for(int i=0;i<eb.length;i++)
            //  sb.append(eb[i]);*/
        pubgenfield.setText(rsak.e.toString());
        
        privgenfield.setText(rsak.d.toString());
        modgenfield.setText(rsak.n.toString());
        
    }//GEN-LAST:event_genkeybuttonActionPerformed

    private void extractbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractbuttonActionPerformed
        // TODO add your handling code here:
        try{
        extract.extraction(new File(browsestegofield.getText()),mdfcodefield.getText(),privatekeyfield.getText(),recmodfield.getText(),new File(outputfield.getText()+"\\OriginalMessage.txt"));
         } catch (Exception ex) {
            Logger.getLogger(intface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_extractbuttonActionPerformed

    private void exitbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbutton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbutton2ActionPerformed

    private void exitbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbutton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbutton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JTextField authcodefield;
    private javax.swing.JButton browseimagebutton;
    private javax.swing.JTextField browseimagefield;
    private javax.swing.JButton browsestegobutton;
    private javax.swing.JTextField browsestegofield;
    private javax.swing.JButton browsetextbutton;
    private javax.swing.JTextField browsetextfield;
    private javax.swing.JButton embedbutton;
    private javax.swing.JButton exitbutton1;
    private javax.swing.JButton exitbutton2;
    private javax.swing.JButton exitbutton3;
    private javax.swing.JButton extractbutton;
    private javax.swing.JButton genkeybutton;
    private javax.swing.JLabel imglabel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JFileChooser jFileChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField keysizefield;
    private javax.swing.JTextField mdfcodefield;
    private javax.swing.JTextField modgenfield;
    private javax.swing.JButton outputbutton;
    private javax.swing.JTextField outputfield;
    private javax.swing.JTextField privatekeyfield;
    private javax.swing.JTextField privgenfield;
    private javax.swing.JTextField pubgenfield;
    private javax.swing.JLabel pubkeylab;
    private javax.swing.JTextField publickeyfield;
    private javax.swing.JTextField recmodfield;
    private javax.swing.JTextField sendmodfield;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
